<?php
error_reporting(0);
session_start();
include_once("connect.php");
$err = "";
$_SESSION['start_time'] = time();

if(!isset($_SESSION["admin_name"]) & !isset($_SESSION["admin_id"])) {
	header("Location:index.php") ; 
	}
?>
<?php
if($_POST['img_upload']=='true') {
$file_exts = array("jpg", "bmp", "jpeg", "gif", "png");
$upload_exts = end(explode(".", $_FILES["file"]["name"]));
if ((($_FILES["file"]["type"] == "image/gif")
|| ($_FILES["file"]["type"] == "image/jpeg")
|| ($_FILES["file"]["type"] == "image/png")
|| ($_FILES["file"]["type"] == "image/pjpeg"))
&& ($_FILES["file"]["size"] < 2000000)
&& in_array($upload_exts, $file_exts))
{
if ($_FILES["file"]["error"] > 0)
{
$err = "Return Code: " . $_FILES["file"]["error"] . "<br>";
}
else
{
/*echo "Upload: " . $_FILES["file"]["name"] . "<br>";
echo "Type: " . $_FILES["file"]["type"] . "<br>";
echo "Size: " . ($_FILES["file"]["size"] / 1024) . " kB<br>";
echo "Temp file: " . $_FILES["file"]["tmp_name"] . "<br>";*/
// Enter your path to upload file here
if (file_exists("icard/" .$_FILES["file"]["name"]))
{
echo "<div class='error'>"."(".$_FILES["file"]["name"].")"." already exists. "."</div>";
}
else
{
move_uploaded_file($_FILES["file"]["tmp_name"], "icard/". $_SESSION["admin_name"].".jpg");
$err = "Image <strong>".$_SESSION["admin_name"].".jpg</strong> Succussfully Uploaded. Thank You!!!";
}
}
}
else
{
$err = "<div class='error'>Invalid file</div>";
}
}
?>


	<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Upload Photo</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>
<script>
function validation(){
if ($( "#req_date" ).val() == "")
}
</script>
</head>
<body  >
<div id="main_container">  
	<div class="right_header" align="right">Welcome <strong><?=$_SESSION["admin_name"]?></strong> | <a href="form.php" >Back</a> | <a href="#">Edit Profile</a> | <a href="#">Earlier Reports</a> | <a href="leave.php">Leave Management</a> | <a href="2015_holidays_in_xtrazero.pdf" target="_blank">Leave Calendar</a> | <a href="https://docs.google.com/spreadsheets/d/1BkKzme29qWS3qoKxW9jbAYnpcKaLqwGuxXyiNo668zU/edit#gid=0" target="_blank">Office Needs</a> | <a href="chpass.php">Change Password</a> | <a href="logout.php">Logout</a></div>
	<p><marquee style="color:red;">**Please use Office Needs option when you need something in office.</marquee></p>
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	 <center>
	<form action="photo_upload.php" method="post" enctype="multipart/form-data" onsubmit="validation();">
	<h1>Upload Your Photo for I-Card </h1>
	<h2>Upload Your Photo for I-Card </h2>
	
	<ul><input type="hidden" name="img_upload" value="true" />
	<? if (file_exists("icard/". $_SESSION["admin_name"].".jpg")) { ?>
	<img src="<?="icard/". $_SESSION["admin_name"].".jpg"?>" height="350px" width="280px" /><br />
	<span style="color:#003300; font-weight:600;" ><?=$err?></span>
	<h3>If You want another photo on your I-Card then Please Upload again.</h3>
	<? } ?>
							<li id="li_1" >
							<input type="file" name="file" id="file">
							</li>
							<li id="li_1" ><input type="submit" value="Upload" /> <input type="reset" />
							</li>
		</ul>
						
	</form>
	<br />
		<div id="footer">
			Generated by <a href="http://www.xtrazero.com">XtraZero@Prakhar</a> <br/>
			Last Updated on Mar 24, 2015
		</div></center>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</div>
	</body>
</html>